baseurl = "https://akmalrashid.com/"
languageCode = "en-us"
title = "Dataaa"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[params]
    description = "A website built using Hugo and blogdown."
    footer = "&copy; [Akmal Abdul Rashid](https://akmalrashid.com/) 2017 | [Github](https://github.com/avkmal) | [Email](https://mail.google.com/mail/?fs=1&view=cm&shva=1&to=akmalabdulrashid@gmail.com)"
